version: '3'

services:
  backend:
    env_file:
      "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "omm-backend"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "omm-frontend"
    ports:
      - "3000:3000"